//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REGLOGINMVC.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddDbData", ReplyAction="http://tempuri.org/IMyService/AddDbDataResponse")]
        bool AddDbData(CustomModel.CommonClass custom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddDbData", ReplyAction="http://tempuri.org/IMyService/AddDbDataResponse")]
        System.Threading.Tasks.Task<bool> AddDbDataAsync(CustomModel.CommonClass custom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/verifyDbUser", ReplyAction="http://tempuri.org/IMyService/verifyDbUserResponse")]
        bool verifyDbUser(CustomModel.CommonClass c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/verifyDbUser", ReplyAction="http://tempuri.org/IMyService/verifyDbUserResponse")]
        System.Threading.Tasks.Task<bool> verifyDbUserAsync(CustomModel.CommonClass c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/userDbDetails", ReplyAction="http://tempuri.org/IMyService/userDbDetailsResponse")]
        CustomModel.CommonClass1[] userDbDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/userDbDetails", ReplyAction="http://tempuri.org/IMyService/userDbDetailsResponse")]
        System.Threading.Tasks.Task<CustomModel.CommonClass1[]> userDbDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/verifyDbEmail", ReplyAction="http://tempuri.org/IMyService/verifyDbEmailResponse")]
        bool verifyDbEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/verifyDbEmail", ReplyAction="http://tempuri.org/IMyService/verifyDbEmailResponse")]
        System.Threading.Tasks.Task<bool> verifyDbEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/Edit", ReplyAction="http://tempuri.org/IMyService/EditResponse")]
        CustomModel.CommonClass1[] Edit(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/Edit", ReplyAction="http://tempuri.org/IMyService/EditResponse")]
        System.Threading.Tasks.Task<CustomModel.CommonClass1[]> EditAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/editDbUser", ReplyAction="http://tempuri.org/IMyService/editDbUserResponse")]
        bool editDbUser(CustomModel.CommonClass1 c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/editDbUser", ReplyAction="http://tempuri.org/IMyService/editDbUserResponse")]
        System.Threading.Tasks.Task<bool> editDbUserAsync(CustomModel.CommonClass1 c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : REGLOGINMVC.ServiceReference1.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<REGLOGINMVC.ServiceReference1.IMyService>, REGLOGINMVC.ServiceReference1.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddDbData(CustomModel.CommonClass custom) {
            return base.Channel.AddDbData(custom);
        }
        
        public System.Threading.Tasks.Task<bool> AddDbDataAsync(CustomModel.CommonClass custom) {
            return base.Channel.AddDbDataAsync(custom);
        }
        
        public bool verifyDbUser(CustomModel.CommonClass c) {
            return base.Channel.verifyDbUser(c);
        }
        
        public System.Threading.Tasks.Task<bool> verifyDbUserAsync(CustomModel.CommonClass c) {
            return base.Channel.verifyDbUserAsync(c);
        }
        
        public CustomModel.CommonClass1[] userDbDetails() {
            return base.Channel.userDbDetails();
        }
        
        public System.Threading.Tasks.Task<CustomModel.CommonClass1[]> userDbDetailsAsync() {
            return base.Channel.userDbDetailsAsync();
        }
        
        public bool verifyDbEmail(string email) {
            return base.Channel.verifyDbEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> verifyDbEmailAsync(string email) {
            return base.Channel.verifyDbEmailAsync(email);
        }
        
        public CustomModel.CommonClass1[] Edit(int id) {
            return base.Channel.Edit(id);
        }
        
        public System.Threading.Tasks.Task<CustomModel.CommonClass1[]> EditAsync(int id) {
            return base.Channel.EditAsync(id);
        }
        
        public bool editDbUser(CustomModel.CommonClass1 c) {
            return base.Channel.editDbUser(c);
        }
        
        public System.Threading.Tasks.Task<bool> editDbUserAsync(CustomModel.CommonClass1 c) {
            return base.Channel.editDbUserAsync(c);
        }
    }
}
