//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int record_Id { get; set; }
        public string Name { get; set; }
        public string TeamMember { get; set; }
        public string ScrumMaster { get; set; }
    }
}
