//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrumMaster
    {
        public int C_record_Id { get; set; }
        public string Name { get; set; }
        public string C_Team_member { get; set; }
        public string Scrum_master { get; set; }
    }
}
